# Generated by Django 3.1 on 2020-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairColouring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Colouring & Highlights',
            },
        ),
        migrations.AlterModelOptions(
            name='haircutting',
            options={'verbose_name': 'Haircuts & Hairdressing'},
        ),
    ]
