# Generated by Django 3.1 on 2020-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20201026_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyebrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Eyebrows & Eyelashes',
            },
        ),
        migrations.CreateModel(
            name='LadysWaxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ladies Waxing',
            },
        ),
        migrations.CreateModel(
            name='MensWaxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Mens Waxing',
            },
        ),
        migrations.CreateModel(
            name='NonPurchasable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Non-Purchasable',
            },
        ),
        migrations.CreateModel(
            name='WaxPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ladies Waxing - Packages',
            },
        ),
    ]
