# Generated by Django 3.1 on 2020-10-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20201026_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonpurchasable',
            options={'verbose_name_plural': 'Non-Purchasable'},
        ),
    ]
