# Generated by Django 3.1.2 on 2020-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20201026_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWorkOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='TeamWorkOne')),
            ],
            options={
                'verbose_name_plural': 'Team Work One',
            },
        ),
        migrations.CreateModel(
            name='TeamWorkThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='TeamWorkThree')),
            ],
            options={
                'verbose_name_plural': 'Team Work Three',
            },
        ),
        migrations.CreateModel(
            name='TeamWorkTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='TeamWorkTwo')),
            ],
            options={
                'verbose_name_plural': 'Team Work Two',
            },
        ),
    ]
