# Generated by Django 3.1.2 on 2020-11-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_teamworkone_teamworkthree_teamworktwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamWorkOne',
        ),
        migrations.DeleteModel(
            name='TeamWorkThree',
        ),
        migrations.DeleteModel(
            name='TeamWorkTwo',
        ),
    ]
