# Generated by Django 3.1.2 on 2020-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_auto_20201112_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamworkone',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teamworkthree',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teamworktwo',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
