# Generated by Django 3.1.2 on 2020-11-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_auto_20201113_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamworkone',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='teamworkthree',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='teamworktwo',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
